name: make
on:
  pull_request:
  push:


jobs:
  call-pytest:
    uses: QCDIS/deleteme/.github/workflows/python-package-conda.yml@main
#    with:
#      environment: deleteme
#    secrets:
#      token: ${{ secrets.REPO_SEC }}