name: make
on:
  pull_request:
  push:


jobs:
  build-linux:
    runs-on: ubuntu-latest
    environment: deleteme
    strategy:
      max-parallel: 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          conda env update --file environment.yml --name base            

      - name: Test with pytest
        env:
          SECRET: ${{ secrets.REPO_SEC }}
        run: |
          conda install pytest
          pytest --ignore=docker
