name: make
on:
  pull_request:
  push:


jobs:
  call-pytest:
    uses: QCDIS/deleteme/.github/workflows/python-package-conda.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      dockerfile: deleteme
      tag: n-a-a-vre-laserfarm
      push: false
    secrets:
      gitlab_username: ${{ secrets.REPO_SEC }}
      gitlab_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}