name: Python Package using Conda

on:
  workflow_call:




jobs:
  build-linux:
    runs-on: ubuntu-latest
    environment: deleteme
    env:
      SECRET: ${{ secrets.REPO_SEC }}

    strategy:
      max-parallel: 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Test with pytest
        run: |
          conda install pytest
          pytest --ignore=docker
